"""Export: single assets, and the game pack with its manifest (spec section 51)."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from ..audio.io import write_audio
from ..core.assets import AudioAsset, PatternAsset, SynthAsset
from ..core.project import Project
from ..core.renderer import Renderer


@dataclass
class ExportProfile:
    name: str = "Generic"
    audio_format: str = "wav"
    music_format: str = "wav"
    bit_depth: int = 16
    sample_rate: int = 44100
    channels: int = 1
    normalize: bool = True
    target_peak: float = 0.95
    layout: dict = field(
        default_factory=lambda: {"sfx": "audio", "music": "music", "patterns": "patterns"}
    )

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "audio_format": self.audio_format,
            "music_format": self.music_format,
            "bit_depth": self.bit_depth,
            "sample_rate": self.sample_rate,
            "channels": self.channels,
            "normalize": self.normalize,
            "target_peak": self.target_peak,
            "layout": self.layout,
        }


EXPORT_PROFILES: dict[str, ExportProfile] = {
    "Generic": ExportProfile("Generic"),
    "Godot": ExportProfile("Godot", "wav", "ogg", 16, 44100),
    "Unity PC": ExportProfile("Unity PC", "wav", "ogg", 16, 48000),
    "Unity Mobile": ExportProfile("Unity Mobile", "wav", "mp3", 16, 44100),
    "Web": ExportProfile("Web", "ogg", "ogg", 16, 44100),
    "Retro Hardware": ExportProfile("Retro Hardware", "wav", "wav", 16, 22050),
}


def export_asset(
    asset,
    project: Project,
    path: str | Path,
    renderer: Renderer | None = None,
    bit_depth: int = 16,
    normalize: bool = False,
) -> Path:
    renderer = renderer or Renderer()
    buf = renderer.render_asset(asset, project)
    if normalize:
        buf = buf.normalized()
    return write_audio(buf, path, bit_depth)


def export_game_pack(
    project: Project,
    directory: str | Path,
    profile: ExportProfile | None = None,
    renderer: Renderer | None = None,
    progress=None,
) -> dict:
    """Write audio, patterns, and a manifest mapping logical names to files."""
    profile = profile or EXPORT_PROFILES["Generic"]
    renderer = renderer or Renderer()
    root = Path(directory)
    root.mkdir(parents=True, exist_ok=True)

    manifest = {
        "project": project.name,
        "profile": profile.name,
        "sample_rate": profile.sample_rate,
        "assets": {},
        "patterns": {},
    }

    renderable = [a for a in project.assets.sorted() if isinstance(a, (SynthAsset, AudioAsset))]
    patterns = [a for a in project.assets.sorted() if isinstance(a, PatternAsset)]
    total = max(1, len(renderable) + len(patterns))
    done = 0

    for asset in renderable:
        is_music = "music" in asset.tags or asset.name.startswith("bgm_")
        sub = profile.layout["music"] if is_music else profile.layout["sfx"]
        fmt = profile.music_format if is_music else profile.audio_format
        out_dir = root / sub
        out_path = out_dir / f"{asset.name}.{fmt}"

        buf = renderer.render_asset(asset, project)
        if profile.sample_rate != buf.sample_rate:
            buf = buf.resampled(profile.sample_rate)
        if profile.channels == 2:
            buf = buf.stereo()
        if profile.normalize:
            buf = buf.normalized(profile.target_peak)
        write_audio(buf, out_path, profile.bit_depth)

        manifest["assets"][asset.name] = {
            "file": str(out_path.relative_to(root)).replace("\\", "/"),
            "uid": asset.uid,
            "duration": round(buf.duration, 6),
            "tags": asset.tags,
        }
        done += 1
        if progress:
            progress(done, total, asset.name)

    for pattern in patterns:
        out_path = root / profile.layout["patterns"] / f"{pattern.name}.json"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(pattern.to_dict(), indent=2), encoding="utf-8")
        manifest["patterns"][pattern.name] = {
            "file": str(out_path.relative_to(root)).replace("\\", "/"),
            "uid": pattern.uid,
        }
        done += 1
        if progress:
            progress(done, total, pattern.name)

    (root / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def export_constants(project: Project, path: str | Path, language: str = "python") -> Path:
    """Generate asset-name constants for a game engine (spec section 69)."""
    path = Path(path)
    names = [a.name for a in project.assets.sorted()]
    if language == "python":
        body = "\n".join(f'{n.upper()} = "{n}"' for n in names)
        text = f'"""Generated by Retro Audio Workstation. Do not edit."""\n\n{body}\n'
    elif language == "csharp":
        body = "\n".join(f'    public const string {n.upper()} = "{n}";' for n in names)
        text = "// Generated by Retro Audio Workstation. Do not edit.\npublic static class RawAudio\n{\n" + body + "\n}\n"
    else:  # gdscript
        body = "\n".join(f'const {n.upper()} = "{n}"' for n in names)
        text = "# Generated by Retro Audio Workstation. Do not edit.\n" + body + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
